# SPDX-FileCopyrightText: Copyright (c) 1993-2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""HTTP proxy routes for serving media generated by internal services.

These routes expose media from internal services (e.g., flux-service, wan-service)
under the same origin as the frontend so browsers can fetch the assets
without resolving container-only hostnames.
"""

from __future__ import annotations

import os
from typing import Mapping

import httpx
from fastapi import APIRouter, HTTPException, Request
from fastapi.responses import StreamingResponse

from logger import logger


media_router = APIRouter()

FLUX_SERVICE_URL = os.getenv("FLUX_SERVICE_URL", "http://flux-service:8080")
WAN_SERVICE_URL = os.getenv("WAN_SERVICE_URL", "http://wan-service:8080")


async def _proxy_stream(upstream_url: str, request: Request, *, identifier: str) -> StreamingResponse:
    """Stream media from an internal service back to the client.

    Range requests are forwarded when provided, but partial content handling
    depends on upstream support. If the upstream service does not honor Range
    headers, the full media will be streamed to the client.
    """

    headers: Mapping[str, str] = {}
    range_header = request.headers.get("range")
    if range_header:
        headers = {"Range": range_header}

    try:
        async with httpx.AsyncClient(timeout=120, follow_redirects=True) as client:
            async with client.stream("GET", upstream_url, headers=headers) as upstream_response:
                logger.info(
                    {
                        "message": "Proxying media request",
                        "upstream_url": upstream_url,
                        "status_code": upstream_response.status_code,
                        "identifier": identifier,
                    }
                )

                if upstream_response.status_code in {404}:
                    raise HTTPException(status_code=404, detail="Media not found")

                if upstream_response.status_code not in {200, 206}:  # 206 for Range responses
                    logger.error(
                        {
                            "message": "Upstream media service error",
                            "upstream_url": upstream_url,
                            "status_code": upstream_response.status_code,
                            "identifier": identifier,
                        }
                    )
                    raise HTTPException(status_code=502, detail="Unable to fetch media from upstream service")

                response_headers = {}
                for header_name in ("content-type", "content-length", "content-range", "accept-ranges"):
                    header_value = upstream_response.headers.get(header_name)
                    if header_value:
                        response_headers[header_name.title()] = header_value

                return StreamingResponse(
                    upstream_response.aiter_bytes(),
                    status_code=upstream_response.status_code,
                    headers=response_headers,
                )
    except HTTPException:
        raise
    except httpx.RequestError as exc:
        logger.error(
            {
                "message": "Media proxy upstream request failed",
                "upstream_url": upstream_url,
                "identifier": identifier,
                "error": str(exc),
            }
        )
        raise HTTPException(status_code=502, detail="Upstream media service unavailable") from exc


@media_router.get("/media/flux/{path:path}")
async def proxy_flux_media(path: str, request: Request) -> StreamingResponse:
    """Proxy media content from the FLUX service."""

    normalized_path = path.lstrip("/")
    upstream_url = f"{FLUX_SERVICE_URL.rstrip('/')}/{normalized_path}"
    return await _proxy_stream(upstream_url, request, identifier=f"flux:{normalized_path}")


@media_router.get("/media/wan/{path:path}")
async def proxy_wan_media(path: str, request: Request) -> StreamingResponse:
    """Proxy media content from the WAN service."""

    normalized_path = path.lstrip("/")
    upstream_url = f"{WAN_SERVICE_URL.rstrip('/')}/{normalized_path}"
    return await _proxy_stream(upstream_url, request, identifier=f"wan:{normalized_path}")

